jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx

language: python
cache: pip
python:
  - "3.6"
  - "3.9"

install:
  - pip install sympy
  - pip install yapf
  - pip install -e "$PWD"

before_script:
  - chmod +x ./.travis/build.sh

script:
  - ./.travis/build.sh