os:
  - linux
#  - osx
dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.9"

install:
  - pip install sympy
  - pip install -e "$PWD"

before_script:
  - chmod +x ./.travis/build.sh

script:
  - ./.travis/build.sh